# Generated by Django 4.2.6 on 2024-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('chat_response', models.TextField()),
            ],
        ),
    ]
