# Generated by Django 4.2.6 on 2024-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='therapy_license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
