# Generated by Django 4.2.6 on 2024-02-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_number',
            new_name='license_number',
        ),
    ]
