# Generated by Django 4.2.6 on 2024-02-29 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_reg_number_user_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_number', models.CharField(max_length=20, null=True)),
                ('transaction_amount', models.FloatField()),
                ('transaction_currency', models.CharField(choices=[('Ksh', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('UGD', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling')], default='Kenyan Shilling', max_length=40)),
                ('transaction_identifier', models.CharField(max_length=255, null=True, unique=True)),
                ('transaction_code', models.CharField(max_length=255, null=True, unique=True)),
                ('transaction_status', models.CharField(choices=[('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('utilised', models.BooleanField(default=False)),
                ('booking_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookingsession')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
