# Generated by Django 4.2.6 on 2024-03-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_choice',
            field=models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors')], max_length=10),
        ),
    ]
