# Generated by Django 4.2.6 on 2024-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_game_player_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_again',
            field=models.BooleanField(default=True),
        ),
    ]
