# Generated by Django 4.2.6 on 2024-03-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_play_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking_session_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.transaction'),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.transaction'),
        ),
    ]
