# Generated by Django 4.2.6 on 2024-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_transaction_booking_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('session_booking', 'Session_booking'), ('therapist_subscription', ' Therapist Subscription')], default='session_booking', max_length=100),
        ),
    ]
