# Generated by Django 4.2.6 on 2024-05-25 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('conducted', 'Conducted')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Donate'), ('session_booking', 'Session_booking'), ('therapist_subscription', ' Therapist Subscription'), ('client_subscription', ' Client Subscription')], default='session_booking', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
