# Generated by Django 4.2.6 on 2024-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookingsession_paid_alter_bookingsession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], default='successful', max_length=20),
        ),
    ]
