# Generated by Django 4.2.6 on 2024-05-25 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('session_booking', 'Session_booking'), ('therapist_subscription', ' Therapist Subscription'), ('client_subscription', ' Client Subscription')], default='session_booking', max_length=100),
        ),
    ]
