# Generated by Django 4.2.6 on 2024-06-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification'),
        ('core', '0014_remove_user_transaction_id_transaction_user_and_more'),
    ]

    operations = [
    ]
